export let keywords = [
  "Minar Cruise",
  "Cochin cruise",
  "Arabian Sea",
  "luxury dining",
  "fine dining",
  "gourmet cuisine",
  "international cuisine",
  "sunset cruise",
  "Kerala tourism",
  "Cochin tourism",
  "Kerala backwaters",
  "Kerala houseboat",
  "gourmet experience",
  "sea adventure",
  "Ernakulam cruises",
  "Kochi cruises",
  "Kerala boat cruises",
  "romantic cruise",
  "family-friendly cruise",
  "adventure cruise",
  "wedding cruise",
  "corporate event cruise",
  "anniversary cruise",
  "best sunset cruise in Cochin",
  "luxury houseboat cruise in Kerala",
  "family-friendly boat tour in Ernakulam",
];
