version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    restart: "always"
    environment:
      POSTGRES_DB: myapp
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5428:5432"

  pgbouncer:
    image: edoburu/pgbouncer:1.18.0
    restart: "always"
    environment:
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_HOST=postgres
      - DB_NAME=myapp
      - POOL_MODE=transaction
      - MAX_CLIENT_CONN=100
      - DEFAULT_POOL_SIZE=20
      - LISTEN_PORT=6432
      - AUTH_TYPE=plain
    ports:
      - "6432:6432"
    depends_on:
      - postgres

volumes:
  postgres_data:
